//
// Generated file, do not edit! Created by nedtool 4.6 from package/signal/signal.msg.
//

#ifndef _WSN_ENERGY_SIGNAL_M_H_
#define _WSN_ENERGY_SIGNAL_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace wsn_energy {

/**
 * Class generated from <tt>package/signal/signal.msg:11</tt> by nedtool.
 * <pre>
 * packet Raw
 * {
 *     bool bitError;
 * 
 *     // 6 octets preamable
 *     int headerLength = 6;
 * 
 *     // fields
 *     // SHR synchronisation header
 *     // 4 octets (4 octets 0x00) preamable sequence
 *     // 1 octet  (1 octet  0xA7) start of frame delimeter (SFD)
 *     // PHR physical header
 *     // 1 octet frame length (does not count it self)
 * 
 *     // 127 octets maximum payload length
 *     // PHY protocol data unit (PPDU)
 *     int maxPayloadLength = 127;
 * }
 * </pre>
 */
class Raw : public ::cPacket
{
  protected:
    bool bitError_var;
    int headerLength_var;
    int maxPayloadLength_var;

  private:
    void copy(const Raw& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Raw&);

  public:
    Raw(const char *name=NULL, int kind=0);
    Raw(const Raw& other);
    virtual ~Raw();
    Raw& operator=(const Raw& other);
    virtual Raw *dup() const {return new Raw(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual bool getBitError() const;
    virtual void setBitError(bool bitError);
    virtual int getHeaderLength() const;
    virtual void setHeaderLength(int headerLength);
    virtual int getMaxPayloadLength() const;
    virtual void setMaxPayloadLength(int maxPayloadLength);
};

inline void doPacking(cCommBuffer *b, Raw& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Raw& obj) {obj.parsimUnpack(b);}

} // namespace wsn_energy

#endif // ifndef _WSN_ENERGY_SIGNAL_M_H_

